# Generated by Django 2.2.5 on 2019-09-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
