# Generated by Django 2.2.5 on 2019-09-04 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0002_auto_20190904_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('city_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='city.City')),
            ],
            options={
                'unique_together': {('name', 'city_id')},
            },
        ),
    ]
