# Generated by Django 2.2.5 on 2019-09-05 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('city', '0004_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='street_id',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='shops', to='city.Street'),
        ),
    ]
